Switch to which -a  (may show multiples)
Top one prevails:
/Users/monty/.swiftly/bin/swift
/usr/bin/swift

diff --git a/bin.dir/bash-path_test b/bin.dir/bash-path_test
--- a/bin.dir/bash-path_test
+++ b/bin.dir/bash-path_test
@@ -11,8 +11,8 @@ echo $PATH | tr ':' '\n'
 echo ""
 
 echo "Checking for tools:"
-which rg || echo "rg not found"
-which swift || echo "swift not found"
+which -a rg || echo "rg not found"
+which -a swift || echo "swift not found"
 echo ""
 
 echo "Checking for directory shortcuts:"
diff --git a/bin.dir/zsh-path_test b/bin.dir/zsh-path_test
--- a/bin.dir/zsh-path_test
+++ b/bin.dir/zsh-path_test
@@ -12,8 +12,8 @@ printf "%s\n" $path
 echo ""
 
 echo "Checking for tools:"
-which rg || echo "rg not found"
-which swift || echo "swift not found"
+which -a rg || echo "rg not found"
+which -a swift || echo "swift not found"
 echo ""
 
 echo "Checking for directory shortcuts:"
